:- use_module('../main').
:- use_module(precond).
:- use_module('../util').

experiment1:-
    statistics(runtime, [Start|_]),
    Phi = until(_, 2, states([[]]), states([[on(a,b)]]), >=, 0.6),
    evaluate(Phi), !,
    statistics(runtime                                      , [Stop|_]),
    print_message(informational, exetime(Start, Stop)).



% TODO: a bug here
experimentXX:-
    statistics(runtime, [Start|_]),
    Phi = next(
            _,
            next(
                _,
                states([[on(a,b)]]),
                >=,
                0.9),
            >=,
            0.9
            ), !,
    evaluate(Phi), !,
    statistics(runtime, [Stop|_]),
    % Res = [_,R|_],
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).


experimentOR:-
    statistics(runtime, [Start|_]),
    Phi = until(_, 2, states([[]]), states([[on(a,b)],[cl(c)]]), >=, 0.6),
    evaluate(Phi), !,
    statistics(runtime, [Stop|_]),
    % Res = [_,R|_],
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).

experimentMOT :-
    statistics(runtime, [Start|_]),
    Phi = until(PhiStates, 3,
            next(_, states([[cl(e)]]), >=, 0.9),
            states([[on(c,d)]]),
            >=, 0.6),
    evaluate(Phi), !,
    allinterpretations(ALLInts), % Produced by SARSgenerator/exp/visualizeSARS.py
    % PhiStates = [_,_,_,_|HH],
    filterhaha(ALLInts, PhiStates, GoodInts),
    printall(PhiStates),
    print_message(informational, goodinterpretations(GoodInts)),
    statistics(runtime, [Stop|_]),
    print_message(informational, exetime(Start, Stop)).

experimentX_iter_1 :-
    statistics(runtime, [Start|_]),
    evaluate(next(_, states([[cl(e)]]), >=, 0.9)), !,
    statistics(runtime, [Stop|_]),
    print_message(informational, exetime(Start, Stop)).

experimentF_iter_1 :-
    statistics(runtime, [Start|_]),
    evaluate(until(_, 1, states([[]]), states([[on(a,b)]]), >=, 0.9)), !,
    statistics(runtime, [Stop|_]),
    print_message(informational, exetime(Start, Stop)).

experimentU_iter_1 :-
    statistics(runtime, [Start|_]),
    evaluate(until(_, 1, states([[on(c,d)]]),states([[on(a,b)]]), >=, 0.9)), !,
    statistics(runtime, [Stop|_]),
    print_message(informational, exetime(Start, Stop)).

experiment2:-
    statistics(runtime, [Start|_]),
    evaluate(until(_, 3, states([[on(c,d)]]), states([[on(a,b)]]), >=, 0.6)), !,
    statistics(runtime, [Stop|_]),
    % Res = [_,_,R|_],
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).

experiment5_inner1 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            4,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    1,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).
experiment5_inner2 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            4,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    2,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).
experiment5_inner3 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            4,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    3,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).
experiment5_inner4 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            4,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    4,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).
experiment5_inner5 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            4,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    5,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).

experiment5_outer1 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            1,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    2,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).

experiment5_outer2 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            2,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    2,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).

experiment5_outer3 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            3,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    2,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).

experiment5_outer4 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            4,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    2,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).

experiment5_outer5 :-
    statistics(runtime, [Start|_]),
    evaluate(
        until(_,
            5,
            states([[cl(a)]]),
            and(
                _,
                states([[on(a,b)]]),
                until(
                    _,
                    2,
                    next(_, states([[cl(e)]]), >=, 0.9),
                    states([[on(c,d)]]),
                    >=, 0.9
                )
            ),
        >=, 0.5)
    ), !,
    statistics(runtime, [Stop|_]),
    % print_message(informational, phistates(Phi)),
    print_message(informational, exetime(Start, Stop)).



message_hook(exetime(Start, Stop), informational, _):-
  Time is (Stop-Start)/1000,
  write("Execution time : "),
  write(Time),
  writeln(" s").

message_hook(iteration(CurrentStep), informational, _):-
    write("Iteration "),
    writeln(CurrentStep).

message_hook(stackusage(Used), informational, _):-
    U is Used/1000000,
    write(U),
    writeln(" mb").

message_hook(partialQtime(Start,Stop), informational, _):-
    Time is (Stop-Start)/1000,
    write("partialQ time : "),
    write(Time),
    writeln(" s").
message_hook(qtime(Start,Stop), informational, _):-
    Time is (Stop-Start)/1000,
    write("       Q time : "),
    write(Time),
    writeln(" s").

without_last(WithLast, WithoutLast) :-
    length(WithLast, L),
    length(WithoutLast, L1),
    L1 is L-1,
    prefix(WithoutLast, WithLast).


message_hook(phistates(Phi), informational, _):-
  Phi =.. [ Functor, PhiStates | Rest ],
  % without_last(Operation, Output),
  nl, nl,
  writeln("query: "), write(Functor), writeln(Rest), nl,
  writeln("answer: "), printall(PhiStates), nl, nl.

message_hook(vf(CurrentVs), informational, _):-
    nl,
    writeln("## value function ##"),
    printall(CurrentVs),
    length(CurrentVs, LCurrentVs),
    write("Number of abstract states: "), writeln(LCurrentVs),
    writeln("########").

qtov(q(Q,A,S,SS), vf_SARS(s_(S),a_(A),r_(Q),ss_(SS))).
qtov(partialQ(Q,A,S,SS), partialQ(s_(S),a_(A),r_(Q),ss_(SS))).
good(E, v(0.0,E)).

message_hook(vfWithAction(QRules), informational, _):-
    nl,
    writeln("## value function with action ##"),
    maplist(qtov, QRules, VRulesAct),
    printall(VRulesAct),
    length(VRulesAct, LVRulesAct),
    write("Number of abstract states: "), writeln(LVRulesAct),
    writeln("########").

message_hook(goodinterpretations(GoodInts), informational, _):-
    writeln("## good interpretations ##"),
    maplist(good, GoodInts, GoodIntsW),
    printall(GoodIntsW),
    length(GoodIntsW, LGoodIntsW),
    write("Number of good interpretations: "), writeln(LGoodIntsW),
    writeln("########").

% message_hook(unfilteredQRules(QRules), informational, _):-
%     nl,
%     writeln("## SARS candidates ##"),
%     printall(QRules),
%     length(QRules, LQRules),
%     write("Number of SARS candidates: "), writeln(LQRules),
%     writeln("########").
message_hook(partialQs(SPQs1, SPQs2), informational, _):-
    length(SPQs1, LSPQs1), length(SPQs2, LSPQs2),
    write("partialQs: "), writeln([LSPQs1, LSPQs2]).

%%
printall([]):- !.
printall([E|R]):-
    writeln(E),
    printall(R),!.

%%
filterhaha([], _, []):-!.
filterhaha([E|ALLInts], PhiStates, [E|GoodInts]):-
    member(PhiState, PhiStates),
    thetasubsumes(PhiState,E),
    filterhaha(ALLInts, PhiStates, GoodInts), !.

filterhaha([_|ALLInts], PhiStates, GoodInts):-
    filterhaha(ALLInts, PhiStates, GoodInts), !.
%
allinterpretations(
[[cl(a),cl(b),cl(c),cl(d),cl(e)],
[cl(a),cl(b),cl(c),cl(d),on(a,e)],
[cl(a),cl(b),cl(c),cl(e),on(a,d)],
[cl(a),cl(b),cl(d),cl(e),on(a,c)],
[cl(a),cl(c),cl(d),cl(e),on(a,b)],
[cl(b),cl(a),cl(c),cl(d),on(b,e)],
[cl(b),cl(a),cl(c),cl(e),on(b,d)],
[cl(b),cl(a),cl(d),cl(e),on(b,c)],
[cl(b),cl(c),cl(d),cl(e),on(b,a)],
[cl(c),cl(a),cl(b),cl(d),on(c,e)],
[cl(c),cl(a),cl(b),cl(e),on(c,d)],
[cl(c),cl(a),cl(d),cl(e),on(c,b)],
[cl(c),cl(b),cl(d),cl(e),on(c,a)],
[cl(d),cl(a),cl(b),cl(c),on(d,e)],
[cl(d),cl(a),cl(b),cl(e),on(d,c)],
[cl(d),cl(a),cl(c),cl(e),on(d,b)],
[cl(d),cl(b),cl(c),cl(e),on(d,a)],
[cl(e),cl(a),cl(b),cl(c),on(e,d)],
[cl(e),cl(a),cl(b),cl(d),on(e,c)],
[cl(e),cl(a),cl(c),cl(d),on(e,b)],
[cl(e),cl(b),cl(c),cl(d),on(e,a)],
[cl(a),cl(b),cl(c),on(a,d),on(b,e)],
[cl(a),cl(b),cl(c),on(a,e),on(b,d)],
[cl(a),cl(b),cl(d),on(a,c),on(b,e)],
[cl(a),cl(b),cl(d),on(a,e),on(b,c)],
[cl(a),cl(b),cl(e),on(a,c),on(b,d)],
[cl(a),cl(b),cl(e),on(a,d),on(b,c)],
[cl(a),cl(c),cl(b),on(a,d),on(c,e)],
[cl(a),cl(c),cl(b),on(a,e),on(c,d)],
[cl(a),cl(c),cl(d),on(a,b),on(c,e)],
[cl(a),cl(c),cl(d),on(a,e),on(c,b)],
[cl(a),cl(c),cl(e),on(a,b),on(c,d)],
[cl(a),cl(c),cl(e),on(a,d),on(c,b)],
[cl(a),cl(d),cl(b),on(a,c),on(d,e)],
[cl(a),cl(d),cl(b),on(a,e),on(d,c)],
[cl(a),cl(d),cl(c),on(a,b),on(d,e)],
[cl(a),cl(d),cl(c),on(a,e),on(d,b)],
[cl(a),cl(d),cl(e),on(a,b),on(d,c)],
[cl(a),cl(d),cl(e),on(a,c),on(d,b)],
[cl(a),cl(e),cl(b),on(a,c),on(e,d)],
[cl(a),cl(e),cl(b),on(a,d),on(e,c)],
[cl(a),cl(e),cl(c),on(a,b),on(e,d)],
[cl(a),cl(e),cl(c),on(a,d),on(e,b)],
[cl(a),cl(e),cl(d),on(a,b),on(e,c)],
[cl(a),cl(e),cl(d),on(a,c),on(e,b)],
[cl(b),cl(c),cl(a),on(b,d),on(c,e)],
[cl(b),cl(c),cl(a),on(b,e),on(c,d)],
[cl(b),cl(c),cl(d),on(b,a),on(c,e)],
[cl(b),cl(c),cl(d),on(b,e),on(c,a)],
[cl(b),cl(c),cl(e),on(b,a),on(c,d)],
[cl(b),cl(c),cl(e),on(b,d),on(c,a)],
[cl(b),cl(d),cl(a),on(b,c),on(d,e)],
[cl(b),cl(d),cl(a),on(b,e),on(d,c)],
[cl(b),cl(d),cl(c),on(b,a),on(d,e)],
[cl(b),cl(d),cl(c),on(b,e),on(d,a)],
[cl(b),cl(d),cl(e),on(b,a),on(d,c)],
[cl(b),cl(d),cl(e),on(b,c),on(d,a)],
[cl(b),cl(e),cl(a),on(b,c),on(e,d)],
[cl(b),cl(e),cl(a),on(b,d),on(e,c)],
[cl(b),cl(e),cl(c),on(b,a),on(e,d)],
[cl(b),cl(e),cl(c),on(b,d),on(e,a)],
[cl(b),cl(e),cl(d),on(b,a),on(e,c)],
[cl(b),cl(e),cl(d),on(b,c),on(e,a)],
[cl(c),cl(d),cl(a),on(c,b),on(d,e)],
[cl(c),cl(d),cl(a),on(c,e),on(d,b)],
[cl(c),cl(d),cl(b),on(c,a),on(d,e)],
[cl(c),cl(d),cl(b),on(c,e),on(d,a)],
[cl(c),cl(d),cl(e),on(c,a),on(d,b)],
[cl(c),cl(d),cl(e),on(c,b),on(d,a)],
[cl(c),cl(e),cl(a),on(c,b),on(e,d)],
[cl(c),cl(e),cl(a),on(c,d),on(e,b)],
[cl(c),cl(e),cl(b),on(c,a),on(e,d)],
[cl(c),cl(e),cl(b),on(c,d),on(e,a)],
[cl(c),cl(e),cl(d),on(c,a),on(e,b)],
[cl(c),cl(e),cl(d),on(c,b),on(e,a)],
[cl(d),cl(e),cl(a),on(d,b),on(e,c)],
[cl(d),cl(e),cl(a),on(d,c),on(e,b)],
[cl(d),cl(e),cl(b),on(d,a),on(e,c)],
[cl(d),cl(e),cl(b),on(d,c),on(e,a)],
[cl(d),cl(e),cl(c),on(d,a),on(e,b)],
[cl(d),cl(e),cl(c),on(d,b),on(e,a)],
[cl(a),cl(b),cl(c),on(a,d),on(d,e)],
[cl(a),cl(b),cl(c),on(a,e),on(e,d)],
[cl(a),cl(b),cl(d),on(a,c),on(c,e)],
[cl(a),cl(b),cl(d),on(a,e),on(e,c)],
[cl(a),cl(b),cl(e),on(a,c),on(c,d)],
[cl(a),cl(b),cl(e),on(a,d),on(d,c)],
[cl(a),cl(c),cl(d),on(a,b),on(b,e)],
[cl(a),cl(c),cl(d),on(a,e),on(e,b)],
[cl(a),cl(c),cl(e),on(a,b),on(b,d)],
[cl(a),cl(c),cl(e),on(a,d),on(d,b)],
[cl(a),cl(d),cl(e),on(a,b),on(b,c)],
[cl(a),cl(d),cl(e),on(a,c),on(c,b)],
[cl(b),cl(a),cl(c),on(b,d),on(d,e)],
[cl(b),cl(a),cl(c),on(b,e),on(e,d)],
[cl(b),cl(a),cl(d),on(b,c),on(c,e)],
[cl(b),cl(a),cl(d),on(b,e),on(e,c)],
[cl(b),cl(a),cl(e),on(b,c),on(c,d)],
[cl(b),cl(a),cl(e),on(b,d),on(d,c)],
[cl(b),cl(c),cl(d),on(b,a),on(a,e)],
[cl(b),cl(c),cl(d),on(b,e),on(e,a)],
[cl(b),cl(c),cl(e),on(b,a),on(a,d)],
[cl(b),cl(c),cl(e),on(b,d),on(d,a)],
[cl(b),cl(d),cl(e),on(b,a),on(a,c)],
[cl(b),cl(d),cl(e),on(b,c),on(c,a)],
[cl(c),cl(a),cl(b),on(c,d),on(d,e)],
[cl(c),cl(a),cl(b),on(c,e),on(e,d)],
[cl(c),cl(a),cl(d),on(c,b),on(b,e)],
[cl(c),cl(a),cl(d),on(c,e),on(e,b)],
[cl(c),cl(a),cl(e),on(c,b),on(b,d)],
[cl(c),cl(a),cl(e),on(c,d),on(d,b)],
[cl(c),cl(b),cl(d),on(c,a),on(a,e)],
[cl(c),cl(b),cl(d),on(c,e),on(e,a)],
[cl(c),cl(b),cl(e),on(c,a),on(a,d)],
[cl(c),cl(b),cl(e),on(c,d),on(d,a)],
[cl(c),cl(d),cl(e),on(c,a),on(a,b)],
[cl(c),cl(d),cl(e),on(c,b),on(b,a)],
[cl(d),cl(a),cl(b),on(d,c),on(c,e)],
[cl(d),cl(a),cl(b),on(d,e),on(e,c)],
[cl(d),cl(a),cl(c),on(d,b),on(b,e)],
[cl(d),cl(a),cl(c),on(d,e),on(e,b)],
[cl(d),cl(a),cl(e),on(d,b),on(b,c)],
[cl(d),cl(a),cl(e),on(d,c),on(c,b)],
[cl(d),cl(b),cl(c),on(d,a),on(a,e)],
[cl(d),cl(b),cl(c),on(d,e),on(e,a)],
[cl(d),cl(b),cl(e),on(d,a),on(a,c)],
[cl(d),cl(b),cl(e),on(d,c),on(c,a)],
[cl(d),cl(c),cl(e),on(d,a),on(a,b)],
[cl(d),cl(c),cl(e),on(d,b),on(b,a)],
[cl(e),cl(a),cl(b),on(e,c),on(c,d)],
[cl(e),cl(a),cl(b),on(e,d),on(d,c)],
[cl(e),cl(a),cl(c),on(e,b),on(b,d)],
[cl(e),cl(a),cl(c),on(e,d),on(d,b)],
[cl(e),cl(a),cl(d),on(e,b),on(b,c)],
[cl(e),cl(a),cl(d),on(e,c),on(c,b)],
[cl(e),cl(b),cl(c),on(e,a),on(a,d)],
[cl(e),cl(b),cl(c),on(e,d),on(d,a)],
[cl(e),cl(b),cl(d),on(e,a),on(a,c)],
[cl(e),cl(b),cl(d),on(e,c),on(c,a)],
[cl(e),cl(c),cl(d),on(e,a),on(a,b)],
[cl(e),cl(c),cl(d),on(e,b),on(b,a)],
[cl(a),cl(b),on(a,c),on(c,d),on(b,e)],
[cl(a),cl(b),on(a,c),on(c,e),on(b,d)],
[cl(a),cl(b),on(a,d),on(d,c),on(b,e)],
[cl(a),cl(b),on(a,d),on(d,e),on(b,c)],
[cl(a),cl(b),on(a,e),on(e,c),on(b,d)],
[cl(a),cl(b),on(a,e),on(e,d),on(b,c)],
[cl(a),cl(c),on(a,b),on(b,d),on(c,e)],
[cl(a),cl(c),on(a,b),on(b,e),on(c,d)],
[cl(a),cl(c),on(a,d),on(d,b),on(c,e)],
[cl(a),cl(c),on(a,d),on(d,e),on(c,b)],
[cl(a),cl(c),on(a,e),on(e,b),on(c,d)],
[cl(a),cl(c),on(a,e),on(e,d),on(c,b)],
[cl(a),cl(d),on(a,b),on(b,c),on(d,e)],
[cl(a),cl(d),on(a,b),on(b,e),on(d,c)],
[cl(a),cl(d),on(a,c),on(c,b),on(d,e)],
[cl(a),cl(d),on(a,c),on(c,e),on(d,b)],
[cl(a),cl(d),on(a,e),on(e,b),on(d,c)],
[cl(a),cl(d),on(a,e),on(e,c),on(d,b)],
[cl(a),cl(e),on(a,b),on(b,c),on(e,d)],
[cl(a),cl(e),on(a,b),on(b,d),on(e,c)],
[cl(a),cl(e),on(a,c),on(c,b),on(e,d)],
[cl(a),cl(e),on(a,c),on(c,d),on(e,b)],
[cl(a),cl(e),on(a,d),on(d,b),on(e,c)],
[cl(a),cl(e),on(a,d),on(d,c),on(e,b)],
[cl(b),cl(a),on(b,c),on(c,d),on(a,e)],
[cl(b),cl(a),on(b,c),on(c,e),on(a,d)],
[cl(b),cl(a),on(b,d),on(d,c),on(a,e)],
[cl(b),cl(a),on(b,d),on(d,e),on(a,c)],
[cl(b),cl(a),on(b,e),on(e,c),on(a,d)],
[cl(b),cl(a),on(b,e),on(e,d),on(a,c)],
[cl(b),cl(c),on(b,a),on(a,d),on(c,e)],
[cl(b),cl(c),on(b,a),on(a,e),on(c,d)],
[cl(b),cl(c),on(b,d),on(d,a),on(c,e)],
[cl(b),cl(c),on(b,d),on(d,e),on(c,a)],
[cl(b),cl(c),on(b,e),on(e,a),on(c,d)],
[cl(b),cl(c),on(b,e),on(e,d),on(c,a)],
[cl(b),cl(d),on(b,a),on(a,c),on(d,e)],
[cl(b),cl(d),on(b,a),on(a,e),on(d,c)],
[cl(b),cl(d),on(b,c),on(c,a),on(d,e)],
[cl(b),cl(d),on(b,c),on(c,e),on(d,a)],
[cl(b),cl(d),on(b,e),on(e,a),on(d,c)],
[cl(b),cl(d),on(b,e),on(e,c),on(d,a)],
[cl(b),cl(e),on(b,a),on(a,c),on(e,d)],
[cl(b),cl(e),on(b,a),on(a,d),on(e,c)],
[cl(b),cl(e),on(b,c),on(c,a),on(e,d)],
[cl(b),cl(e),on(b,c),on(c,d),on(e,a)],
[cl(b),cl(e),on(b,d),on(d,a),on(e,c)],
[cl(b),cl(e),on(b,d),on(d,c),on(e,a)],
[cl(c),cl(a),on(c,b),on(b,d),on(a,e)],
[cl(c),cl(a),on(c,b),on(b,e),on(a,d)],
[cl(c),cl(a),on(c,d),on(d,b),on(a,e)],
[cl(c),cl(a),on(c,d),on(d,e),on(a,b)],
[cl(c),cl(a),on(c,e),on(e,b),on(a,d)],
[cl(c),cl(a),on(c,e),on(e,d),on(a,b)],
[cl(c),cl(b),on(c,a),on(a,d),on(b,e)],
[cl(c),cl(b),on(c,a),on(a,e),on(b,d)],
[cl(c),cl(b),on(c,d),on(d,a),on(b,e)],
[cl(c),cl(b),on(c,d),on(d,e),on(b,a)],
[cl(c),cl(b),on(c,e),on(e,a),on(b,d)],
[cl(c),cl(b),on(c,e),on(e,d),on(b,a)],
[cl(c),cl(d),on(c,a),on(a,b),on(d,e)],
[cl(c),cl(d),on(c,a),on(a,e),on(d,b)],
[cl(c),cl(d),on(c,b),on(b,a),on(d,e)],
[cl(c),cl(d),on(c,b),on(b,e),on(d,a)],
[cl(c),cl(d),on(c,e),on(e,a),on(d,b)],
[cl(c),cl(d),on(c,e),on(e,b),on(d,a)],
[cl(c),cl(e),on(c,a),on(a,b),on(e,d)],
[cl(c),cl(e),on(c,a),on(a,d),on(e,b)],
[cl(c),cl(e),on(c,b),on(b,a),on(e,d)],
[cl(c),cl(e),on(c,b),on(b,d),on(e,a)],
[cl(c),cl(e),on(c,d),on(d,a),on(e,b)],
[cl(c),cl(e),on(c,d),on(d,b),on(e,a)],
[cl(d),cl(a),on(d,b),on(b,c),on(a,e)],
[cl(d),cl(a),on(d,b),on(b,e),on(a,c)],
[cl(d),cl(a),on(d,c),on(c,b),on(a,e)],
[cl(d),cl(a),on(d,c),on(c,e),on(a,b)],
[cl(d),cl(a),on(d,e),on(e,b),on(a,c)],
[cl(d),cl(a),on(d,e),on(e,c),on(a,b)],
[cl(d),cl(b),on(d,a),on(a,c),on(b,e)],
[cl(d),cl(b),on(d,a),on(a,e),on(b,c)],
[cl(d),cl(b),on(d,c),on(c,a),on(b,e)],
[cl(d),cl(b),on(d,c),on(c,e),on(b,a)],
[cl(d),cl(b),on(d,e),on(e,a),on(b,c)],
[cl(d),cl(b),on(d,e),on(e,c),on(b,a)],
[cl(d),cl(c),on(d,a),on(a,b),on(c,e)],
[cl(d),cl(c),on(d,a),on(a,e),on(c,b)],
[cl(d),cl(c),on(d,b),on(b,a),on(c,e)],
[cl(d),cl(c),on(d,b),on(b,e),on(c,a)],
[cl(d),cl(c),on(d,e),on(e,a),on(c,b)],
[cl(d),cl(c),on(d,e),on(e,b),on(c,a)],
[cl(d),cl(e),on(d,a),on(a,b),on(e,c)],
[cl(d),cl(e),on(d,a),on(a,c),on(e,b)],
[cl(d),cl(e),on(d,b),on(b,a),on(e,c)],
[cl(d),cl(e),on(d,b),on(b,c),on(e,a)],
[cl(d),cl(e),on(d,c),on(c,a),on(e,b)],
[cl(d),cl(e),on(d,c),on(c,b),on(e,a)],
[cl(e),cl(a),on(e,b),on(b,c),on(a,d)],
[cl(e),cl(a),on(e,b),on(b,d),on(a,c)],
[cl(e),cl(a),on(e,c),on(c,b),on(a,d)],
[cl(e),cl(a),on(e,c),on(c,d),on(a,b)],
[cl(e),cl(a),on(e,d),on(d,b),on(a,c)],
[cl(e),cl(a),on(e,d),on(d,c),on(a,b)],
[cl(e),cl(b),on(e,a),on(a,c),on(b,d)],
[cl(e),cl(b),on(e,a),on(a,d),on(b,c)],
[cl(e),cl(b),on(e,c),on(c,a),on(b,d)],
[cl(e),cl(b),on(e,c),on(c,d),on(b,a)],
[cl(e),cl(b),on(e,d),on(d,a),on(b,c)],
[cl(e),cl(b),on(e,d),on(d,c),on(b,a)],
[cl(e),cl(c),on(e,a),on(a,b),on(c,d)],
[cl(e),cl(c),on(e,a),on(a,d),on(c,b)],
[cl(e),cl(c),on(e,b),on(b,a),on(c,d)],
[cl(e),cl(c),on(e,b),on(b,d),on(c,a)],
[cl(e),cl(c),on(e,d),on(d,a),on(c,b)],
[cl(e),cl(c),on(e,d),on(d,b),on(c,a)],
[cl(e),cl(d),on(e,a),on(a,b),on(d,c)],
[cl(e),cl(d),on(e,a),on(a,c),on(d,b)],
[cl(e),cl(d),on(e,b),on(b,a),on(d,c)],
[cl(e),cl(d),on(e,b),on(b,c),on(d,a)],
[cl(e),cl(d),on(e,c),on(c,a),on(d,b)],
[cl(e),cl(d),on(e,c),on(c,b),on(d,a)],
[cl(a),cl(b),on(a,c),on(c,d),on(d,e)],
[cl(a),cl(b),on(a,c),on(c,e),on(e,d)],
[cl(a),cl(b),on(a,d),on(d,c),on(c,e)],
[cl(a),cl(b),on(a,d),on(d,e),on(e,c)],
[cl(a),cl(b),on(a,e),on(e,c),on(c,d)],
[cl(a),cl(b),on(a,e),on(e,d),on(d,c)],
[cl(a),cl(c),on(a,b),on(b,d),on(d,e)],
[cl(a),cl(c),on(a,b),on(b,e),on(e,d)],
[cl(a),cl(c),on(a,d),on(d,b),on(b,e)],
[cl(a),cl(c),on(a,d),on(d,e),on(e,b)],
[cl(a),cl(c),on(a,e),on(e,b),on(b,d)],
[cl(a),cl(c),on(a,e),on(e,d),on(d,b)],
[cl(a),cl(d),on(a,b),on(b,c),on(c,e)],
[cl(a),cl(d),on(a,b),on(b,e),on(e,c)],
[cl(a),cl(d),on(a,c),on(c,b),on(b,e)],
[cl(a),cl(d),on(a,c),on(c,e),on(e,b)],
[cl(a),cl(d),on(a,e),on(e,b),on(b,c)],
[cl(a),cl(d),on(a,e),on(e,c),on(c,b)],
[cl(a),cl(e),on(a,b),on(b,c),on(c,d)],
[cl(a),cl(e),on(a,b),on(b,d),on(d,c)],
[cl(a),cl(e),on(a,c),on(c,b),on(b,d)],
[cl(a),cl(e),on(a,c),on(c,d),on(d,b)],
[cl(a),cl(e),on(a,d),on(d,b),on(b,c)],
[cl(a),cl(e),on(a,d),on(d,c),on(c,b)],
[cl(b),cl(a),on(b,c),on(c,d),on(d,e)],
[cl(b),cl(a),on(b,c),on(c,e),on(e,d)],
[cl(b),cl(a),on(b,d),on(d,c),on(c,e)],
[cl(b),cl(a),on(b,d),on(d,e),on(e,c)],
[cl(b),cl(a),on(b,e),on(e,c),on(c,d)],
[cl(b),cl(a),on(b,e),on(e,d),on(d,c)],
[cl(b),cl(c),on(b,a),on(a,d),on(d,e)],
[cl(b),cl(c),on(b,a),on(a,e),on(e,d)],
[cl(b),cl(c),on(b,d),on(d,a),on(a,e)],
[cl(b),cl(c),on(b,d),on(d,e),on(e,a)],
[cl(b),cl(c),on(b,e),on(e,a),on(a,d)],
[cl(b),cl(c),on(b,e),on(e,d),on(d,a)],
[cl(b),cl(d),on(b,a),on(a,c),on(c,e)],
[cl(b),cl(d),on(b,a),on(a,e),on(e,c)],
[cl(b),cl(d),on(b,c),on(c,a),on(a,e)],
[cl(b),cl(d),on(b,c),on(c,e),on(e,a)],
[cl(b),cl(d),on(b,e),on(e,a),on(a,c)],
[cl(b),cl(d),on(b,e),on(e,c),on(c,a)],
[cl(b),cl(e),on(b,a),on(a,c),on(c,d)],
[cl(b),cl(e),on(b,a),on(a,d),on(d,c)],
[cl(b),cl(e),on(b,c),on(c,a),on(a,d)],
[cl(b),cl(e),on(b,c),on(c,d),on(d,a)],
[cl(b),cl(e),on(b,d),on(d,a),on(a,c)],
[cl(b),cl(e),on(b,d),on(d,c),on(c,a)],
[cl(c),cl(a),on(c,b),on(b,d),on(d,e)],
[cl(c),cl(a),on(c,b),on(b,e),on(e,d)],
[cl(c),cl(a),on(c,d),on(d,b),on(b,e)],
[cl(c),cl(a),on(c,d),on(d,e),on(e,b)],
[cl(c),cl(a),on(c,e),on(e,b),on(b,d)],
[cl(c),cl(a),on(c,e),on(e,d),on(d,b)],
[cl(c),cl(b),on(c,a),on(a,d),on(d,e)],
[cl(c),cl(b),on(c,a),on(a,e),on(e,d)],
[cl(c),cl(b),on(c,d),on(d,a),on(a,e)],
[cl(c),cl(b),on(c,d),on(d,e),on(e,a)],
[cl(c),cl(b),on(c,e),on(e,a),on(a,d)],
[cl(c),cl(b),on(c,e),on(e,d),on(d,a)],
[cl(c),cl(d),on(c,a),on(a,b),on(b,e)],
[cl(c),cl(d),on(c,a),on(a,e),on(e,b)],
[cl(c),cl(d),on(c,b),on(b,a),on(a,e)],
[cl(c),cl(d),on(c,b),on(b,e),on(e,a)],
[cl(c),cl(d),on(c,e),on(e,a),on(a,b)],
[cl(c),cl(d),on(c,e),on(e,b),on(b,a)],
[cl(c),cl(e),on(c,a),on(a,b),on(b,d)],
[cl(c),cl(e),on(c,a),on(a,d),on(d,b)],
[cl(c),cl(e),on(c,b),on(b,a),on(a,d)],
[cl(c),cl(e),on(c,b),on(b,d),on(d,a)],
[cl(c),cl(e),on(c,d),on(d,a),on(a,b)],
[cl(c),cl(e),on(c,d),on(d,b),on(b,a)],
[cl(d),cl(a),on(d,b),on(b,c),on(c,e)],
[cl(d),cl(a),on(d,b),on(b,e),on(e,c)],
[cl(d),cl(a),on(d,c),on(c,b),on(b,e)],
[cl(d),cl(a),on(d,c),on(c,e),on(e,b)],
[cl(d),cl(a),on(d,e),on(e,b),on(b,c)],
[cl(d),cl(a),on(d,e),on(e,c),on(c,b)],
[cl(d),cl(b),on(d,a),on(a,c),on(c,e)],
[cl(d),cl(b),on(d,a),on(a,e),on(e,c)],
[cl(d),cl(b),on(d,c),on(c,a),on(a,e)],
[cl(d),cl(b),on(d,c),on(c,e),on(e,a)],
[cl(d),cl(b),on(d,e),on(e,a),on(a,c)],
[cl(d),cl(b),on(d,e),on(e,c),on(c,a)],
[cl(d),cl(c),on(d,a),on(a,b),on(b,e)],
[cl(d),cl(c),on(d,a),on(a,e),on(e,b)],
[cl(d),cl(c),on(d,b),on(b,a),on(a,e)],
[cl(d),cl(c),on(d,b),on(b,e),on(e,a)],
[cl(d),cl(c),on(d,e),on(e,a),on(a,b)],
[cl(d),cl(c),on(d,e),on(e,b),on(b,a)],
[cl(d),cl(e),on(d,a),on(a,b),on(b,c)],
[cl(d),cl(e),on(d,a),on(a,c),on(c,b)],
[cl(d),cl(e),on(d,b),on(b,a),on(a,c)],
[cl(d),cl(e),on(d,b),on(b,c),on(c,a)],
[cl(d),cl(e),on(d,c),on(c,a),on(a,b)],
[cl(d),cl(e),on(d,c),on(c,b),on(b,a)],
[cl(e),cl(a),on(e,b),on(b,c),on(c,d)],
[cl(e),cl(a),on(e,b),on(b,d),on(d,c)],
[cl(e),cl(a),on(e,c),on(c,b),on(b,d)],
[cl(e),cl(a),on(e,c),on(c,d),on(d,b)],
[cl(e),cl(a),on(e,d),on(d,b),on(b,c)],
[cl(e),cl(a),on(e,d),on(d,c),on(c,b)],
[cl(e),cl(b),on(e,a),on(a,c),on(c,d)],
[cl(e),cl(b),on(e,a),on(a,d),on(d,c)],
[cl(e),cl(b),on(e,c),on(c,a),on(a,d)],
[cl(e),cl(b),on(e,c),on(c,d),on(d,a)],
[cl(e),cl(b),on(e,d),on(d,a),on(a,c)],
[cl(e),cl(b),on(e,d),on(d,c),on(c,a)],
[cl(e),cl(c),on(e,a),on(a,b),on(b,d)],
[cl(e),cl(c),on(e,a),on(a,d),on(d,b)],
[cl(e),cl(c),on(e,b),on(b,a),on(a,d)],
[cl(e),cl(c),on(e,b),on(b,d),on(d,a)],
[cl(e),cl(c),on(e,d),on(d,a),on(a,b)],
[cl(e),cl(c),on(e,d),on(d,b),on(b,a)],
[cl(e),cl(d),on(e,a),on(a,b),on(b,c)],
[cl(e),cl(d),on(e,a),on(a,c),on(c,b)],
[cl(e),cl(d),on(e,b),on(b,a),on(a,c)],
[cl(e),cl(d),on(e,b),on(b,c),on(c,a)],
[cl(e),cl(d),on(e,c),on(c,a),on(a,b)],
[cl(e),cl(d),on(e,c),on(c,b),on(b,a)],
[cl(a),on(a,b),on(b,c),on(c,d),on(d,e)],
[cl(a),on(a,b),on(b,c),on(c,e),on(e,d)],
[cl(a),on(a,b),on(b,d),on(d,c),on(c,e)],
[cl(a),on(a,b),on(b,d),on(d,e),on(e,c)],
[cl(a),on(a,b),on(b,e),on(e,c),on(c,d)],
[cl(a),on(a,b),on(b,e),on(e,d),on(d,c)],
[cl(a),on(a,c),on(c,b),on(b,d),on(d,e)],
[cl(a),on(a,c),on(c,b),on(b,e),on(e,d)],
[cl(a),on(a,c),on(c,d),on(d,b),on(b,e)],
[cl(a),on(a,c),on(c,d),on(d,e),on(e,b)],
[cl(a),on(a,c),on(c,e),on(e,b),on(b,d)],
[cl(a),on(a,c),on(c,e),on(e,d),on(d,b)],
[cl(a),on(a,d),on(d,b),on(b,c),on(c,e)],
[cl(a),on(a,d),on(d,b),on(b,e),on(e,c)],
[cl(a),on(a,d),on(d,c),on(c,b),on(b,e)],
[cl(a),on(a,d),on(d,c),on(c,e),on(e,b)],
[cl(a),on(a,d),on(d,e),on(e,b),on(b,c)],
[cl(a),on(a,d),on(d,e),on(e,c),on(c,b)],
[cl(a),on(a,e),on(e,b),on(b,c),on(c,d)],
[cl(a),on(a,e),on(e,b),on(b,d),on(d,c)],
[cl(a),on(a,e),on(e,c),on(c,b),on(b,d)],
[cl(a),on(a,e),on(e,c),on(c,d),on(d,b)],
[cl(a),on(a,e),on(e,d),on(d,b),on(b,c)],
[cl(a),on(a,e),on(e,d),on(d,c),on(c,b)],
[cl(b),on(b,a),on(a,c),on(c,d),on(d,e)],
[cl(b),on(b,a),on(a,c),on(c,e),on(e,d)],
[cl(b),on(b,a),on(a,d),on(d,c),on(c,e)],
[cl(b),on(b,a),on(a,d),on(d,e),on(e,c)],
[cl(b),on(b,a),on(a,e),on(e,c),on(c,d)],
[cl(b),on(b,a),on(a,e),on(e,d),on(d,c)],
[cl(b),on(b,c),on(c,a),on(a,d),on(d,e)],
[cl(b),on(b,c),on(c,a),on(a,e),on(e,d)],
[cl(b),on(b,c),on(c,d),on(d,a),on(a,e)],
[cl(b),on(b,c),on(c,d),on(d,e),on(e,a)],
[cl(b),on(b,c),on(c,e),on(e,a),on(a,d)],
[cl(b),on(b,c),on(c,e),on(e,d),on(d,a)],
[cl(b),on(b,d),on(d,a),on(a,c),on(c,e)],
[cl(b),on(b,d),on(d,a),on(a,e),on(e,c)],
[cl(b),on(b,d),on(d,c),on(c,a),on(a,e)],
[cl(b),on(b,d),on(d,c),on(c,e),on(e,a)],
[cl(b),on(b,d),on(d,e),on(e,a),on(a,c)],
[cl(b),on(b,d),on(d,e),on(e,c),on(c,a)],
[cl(b),on(b,e),on(e,a),on(a,c),on(c,d)],
[cl(b),on(b,e),on(e,a),on(a,d),on(d,c)],
[cl(b),on(b,e),on(e,c),on(c,a),on(a,d)],
[cl(b),on(b,e),on(e,c),on(c,d),on(d,a)],
[cl(b),on(b,e),on(e,d),on(d,a),on(a,c)],
[cl(b),on(b,e),on(e,d),on(d,c),on(c,a)],
[cl(c),on(c,a),on(a,b),on(b,d),on(d,e)],
[cl(c),on(c,a),on(a,b),on(b,e),on(e,d)],
[cl(c),on(c,a),on(a,d),on(d,b),on(b,e)],
[cl(c),on(c,a),on(a,d),on(d,e),on(e,b)],
[cl(c),on(c,a),on(a,e),on(e,b),on(b,d)],
[cl(c),on(c,a),on(a,e),on(e,d),on(d,b)],
[cl(c),on(c,b),on(b,a),on(a,d),on(d,e)],
[cl(c),on(c,b),on(b,a),on(a,e),on(e,d)],
[cl(c),on(c,b),on(b,d),on(d,a),on(a,e)],
[cl(c),on(c,b),on(b,d),on(d,e),on(e,a)],
[cl(c),on(c,b),on(b,e),on(e,a),on(a,d)],
[cl(c),on(c,b),on(b,e),on(e,d),on(d,a)],
[cl(c),on(c,d),on(d,a),on(a,b),on(b,e)],
[cl(c),on(c,d),on(d,a),on(a,e),on(e,b)],
[cl(c),on(c,d),on(d,b),on(b,a),on(a,e)],
[cl(c),on(c,d),on(d,b),on(b,e),on(e,a)],
[cl(c),on(c,d),on(d,e),on(e,a),on(a,b)],
[cl(c),on(c,d),on(d,e),on(e,b),on(b,a)],
[cl(c),on(c,e),on(e,a),on(a,b),on(b,d)],
[cl(c),on(c,e),on(e,a),on(a,d),on(d,b)],
[cl(c),on(c,e),on(e,b),on(b,a),on(a,d)],
[cl(c),on(c,e),on(e,b),on(b,d),on(d,a)],
[cl(c),on(c,e),on(e,d),on(d,a),on(a,b)],
[cl(c),on(c,e),on(e,d),on(d,b),on(b,a)],
[cl(d),on(d,a),on(a,b),on(b,c),on(c,e)],
[cl(d),on(d,a),on(a,b),on(b,e),on(e,c)],
[cl(d),on(d,a),on(a,c),on(c,b),on(b,e)],
[cl(d),on(d,a),on(a,c),on(c,e),on(e,b)],
[cl(d),on(d,a),on(a,e),on(e,b),on(b,c)],
[cl(d),on(d,a),on(a,e),on(e,c),on(c,b)],
[cl(d),on(d,b),on(b,a),on(a,c),on(c,e)],
[cl(d),on(d,b),on(b,a),on(a,e),on(e,c)],
[cl(d),on(d,b),on(b,c),on(c,a),on(a,e)],
[cl(d),on(d,b),on(b,c),on(c,e),on(e,a)],
[cl(d),on(d,b),on(b,e),on(e,a),on(a,c)],
[cl(d),on(d,b),on(b,e),on(e,c),on(c,a)],
[cl(d),on(d,c),on(c,a),on(a,b),on(b,e)],
[cl(d),on(d,c),on(c,a),on(a,e),on(e,b)],
[cl(d),on(d,c),on(c,b),on(b,a),on(a,e)],
[cl(d),on(d,c),on(c,b),on(b,e),on(e,a)],
[cl(d),on(d,c),on(c,e),on(e,a),on(a,b)],
[cl(d),on(d,c),on(c,e),on(e,b),on(b,a)],
[cl(d),on(d,e),on(e,a),on(a,b),on(b,c)],
[cl(d),on(d,e),on(e,a),on(a,c),on(c,b)],
[cl(d),on(d,e),on(e,b),on(b,a),on(a,c)],
[cl(d),on(d,e),on(e,b),on(b,c),on(c,a)],
[cl(d),on(d,e),on(e,c),on(c,a),on(a,b)],
[cl(d),on(d,e),on(e,c),on(c,b),on(b,a)],
[cl(e),on(e,a),on(a,b),on(b,c),on(c,d)],
[cl(e),on(e,a),on(a,b),on(b,d),on(d,c)],
[cl(e),on(e,a),on(a,c),on(c,b),on(b,d)],
[cl(e),on(e,a),on(a,c),on(c,d),on(d,b)],
[cl(e),on(e,a),on(a,d),on(d,b),on(b,c)],
[cl(e),on(e,a),on(a,d),on(d,c),on(c,b)],
[cl(e),on(e,b),on(b,a),on(a,c),on(c,d)],
[cl(e),on(e,b),on(b,a),on(a,d),on(d,c)],
[cl(e),on(e,b),on(b,c),on(c,a),on(a,d)],
[cl(e),on(e,b),on(b,c),on(c,d),on(d,a)],
[cl(e),on(e,b),on(b,d),on(d,a),on(a,c)],
[cl(e),on(e,b),on(b,d),on(d,c),on(c,a)],
[cl(e),on(e,c),on(c,a),on(a,b),on(b,d)],
[cl(e),on(e,c),on(c,a),on(a,d),on(d,b)],
[cl(e),on(e,c),on(c,b),on(b,a),on(a,d)],
[cl(e),on(e,c),on(c,b),on(b,d),on(d,a)],
[cl(e),on(e,c),on(c,d),on(d,a),on(a,b)],
[cl(e),on(e,c),on(c,d),on(d,b),on(b,a)],
[cl(e),on(e,d),on(d,a),on(a,b),on(b,c)],
[cl(e),on(e,d),on(d,a),on(a,c),on(c,b)],
[cl(e),on(e,d),on(d,b),on(b,a),on(a,c)],
[cl(e),on(e,d),on(d,b),on(b,c),on(c,a)],
[cl(e),on(e,d),on(d,c),on(c,a),on(a,b)],
[cl(e),on(e,d),on(d,c),on(c,b),on(b,a)]]
).
